isomerpages/mlaw-io

_config.yml, _data/navigation.yml, pages/contact-us.md
Change eservices link for gcc migration on 24 Nov 2019.
=> Change of eservices link for gcc migration

_bankruptcy/2-alternatives-to-bankruptcy.md
Included VWOs contacts under para 5
=> Update Alternatives to Bankruptcy

_bankruptcy/4a2-impact-of-bankruptcy.md
Edited as per requested by mgmt
=> Edited Part 8

_bankruptcy/7-statistics.md
please assist to approve the pull request.
=> IID Dec 2019 stats

_bankruptcy/2-alternatives-to-bankruptcy.md
=> amended spelling error

_bankruptcy/6b-forms1.md
Updated link to the correct document
=> Migration Error

_bankruptcy/6a-forms.md, _bankruptcy/6b-forms1.md, _bankruptcy/reduction-of-monthly-instalment-or-contribution
=> Updated links

_bankruptcy/covid-19-faq.md, _debt-repayment-scheme/covid-19-faq.md
=> Updated the FAQ after approval by 2D IIDRSD

_bankruptcy/covid-19-faq.md
=> Updated COVID-19 FAQs

_bankruptcy/7-statistics.md
Jonathan requested to remove 2019 IID statistics. For your approval, please.
=> Updates to Statistic page

_bankruptcy/4a3-responsibilities-and-rights.md, _bankruptcy/5d-information-for-creditors.md, _corporate-insolvency/2-information-for-the-creditors-of-a-company-in-liquidation.md, _debt-repayment-scheme/2-information-for-debtors.md, index.md, pages/contact-us.md
=> Proposed changes by FOA

_bankruptcy/5d-information-for-creditors.md
=> For approval

_debt-repayment-scheme/0-about-debt-repayment-scheme.md, _debt-repayment-scheme/2-information-for-debtors.md, _debt-repayment-scheme/3-information-for-creditors.md, _debt-repayment-scheme/6-covid-19-faq.md
=> DRS update - IRDA

_bankruptcy/91-covid-19-faq.md
=> Updates to COVID FAQ

_bankruptcy/4a2-impact-of-bankruptcy.md
=> Updated IID's FAQ

_bankruptcy/5c-information-for-private-trustees.md
=> Uploaded PTIB Portal 2.0 Guide

_bankruptcy/5c-information-for-private-trustees.md
=> Amend heading

_bankruptcy/Information for Bankrupts/assets-of-a-bankrupt.md
=> Use of CPF to Buy Private Property

_debt-repayment-scheme/Forms/forms-for-administration.md
=> DRS - Annex B

_bankruptcy/statistics.md
=> Update file: statistics.md

_bankruptcy/statistics.md
=>  IID Statistics for Website (July 2022)

_bankruptcy/statistics.md
=> IID Stats August 2022

_bankruptcy/Information for Bankrupts/responsibilities-and-rights-of-a-bankrupt.md
Dear Ms Zainuirah,
For your approval please. Thank you.
=> Update file: responsibilities-and-rights-of-a-bankrupt.md

_bankruptcy/Information for Bankrupts/assets-of-a-bankrupt.md, _debt-repayment-scheme/information-for-debtors.md, index.md
=> Update file: index.md

_debt-repayment-scheme/Forms/forms-for-administration.md
Hi Ms Zainuirah, 
For your approval please.
=> Removal of debtor

_bankruptcy/Bankruptcy Notification/For Country Clubs.md, _bankruptcy/Bankruptcy Notification/For Securities Firms.md
For your approval please. Thank you.
=> 7 sub folders

_bankruptcy/Bankruptcy Notification/For Government Departments.md
=> For Government Departments

_bankruptcy/Bankruptcy Notification/For Insurance Companies.md
=> Insurance Companies

_bankruptcy/Bankruptcy Notification/For Securities Firms.md
Hi Serene, for your approval please. Thanks!
=> For Securities Firms

_bankruptcy/Bankruptcy Notification/For Telecommunication Service Providers.md
=> Telecommunication Service Providers

_bankruptcy/Bankruptcy Notification/For Country Clubs.md
=> Country Clubs

_bankruptcy/statistics.md
Hi Serene, for your approval pls. Thank you!
=> IID Stats Feb 2023

_bankruptcy/Bankruptcy Notification/For Banks.md, _bankruptcy/Bankruptcy Notification/For CDP.md, _bankruptcy/Bankruptcy Notification/For Country Clubs.md, _bankruptcy/Bankruptcy Notification/For Government Departments.md, _bankruptcy/Bankruptcy Notification/For Insurance Companies.md, _bankruptcy/Bankruptcy Notification/For Securities Firms.md, _bankruptcy/Bankruptcy Notification/For Telecommunication Service Providers.md, _bankruptcy/Bankruptcy Rehabilitation Programme by Credit Counselling Singapore (CCS).md, _bankruptcy/Forms/br-forms-irda-wef-30-july-2020.md, _bankruptcy/Forms/forms-for-administration.md, _bankruptcy/Forms/pir-forms-irda-wef-30-july-2020.md, _bankruptcy/Information for Bankrupts/responsibilities-and-rights-of-a-bankrupt.md, _bankruptcy/covid-19-faq.md, _bankruptcy/irda-faq.md, _config.yml, _corporate-insolvency/irda-faq.md, _corporate-insolvency/sip-faq.md, _debt-repayment-scheme/Forms/forms-insolvency-restructuring-and-dissolution-act-wef-30-july-2020.md, _debt-repayment-scheme/covid-19-faq.md, _debt-repayment-scheme/drs-flowchart.md, _debt-repayment-scheme/irda-faq.md
Hi Serene, for your approval please. Thank you.
=> Removal of Categorising and Zones

_bankruptcy/Information for Stakeholders/information-for-private-trustees.md
Dear Serene, For your approval please. Thank you.
=> Removal of PTIB Portal user guide

_bankruptcy/Information for Bankrupts/discharge-from-bankruptcy.md, _bankruptcy/Information for Bankrupts/responsibilities-and-rights-of-a-bankrupt.md
Dear Serene, for your approval please. Thank you.
=> Proposal to remove/amend information from website

_bankruptcy/Information for Bankrupts/assets-of-a-bankrupt.md
Hi Serene, please assist to approve. Thank you.
=> Amend Information for bankrupt (HDB)

_bankruptcy/pre-bankruptcy.md
=> Pre-Bankruptcy

_bankruptcy/Filing for Bankruptcy.md, _bankruptcy/collection.yml
=> Filing for Bankruptcy

_bankruptcy/Information for Stakeholders/information-for-creditors.md, _bankruptcy/alternatives-to-bankruptcy.md
=> Delete: Filing for bankruptcy

_debt-repayment-scheme/information-for-debtors.md
Hi Zai, 
For approval pls. Thank you.
Serene
=> Update to DRS - Information for Debtors

_bankruptcy/Forms/pir forms irda wef 30 july 2020.md, _bankruptcy/collection.yml
Dear Zai, 
For approval pls. Thank you.
=> Bankruptcy - PIR Forms

_debt-repayment-scheme/information-for-creditors.md
=> PD for DRS

_bankruptcy/Annulment and Discharge Listings.md, _bankruptcy/Bankruptcy Orders Made.md
=> Annulment and Discharge Listings

_unclaimed-monies/bankruptcy.md
=> unclaimed monies

_debt-repayment-scheme/pre-bankruptcy.md
=> to remove Debtor's journey

_bankruptcy/Information for Bankrupts/bankruptcy-information-sheet-for-debtors-bankrupts.md
Hi Serene, please assist to approve the request. Thank you
=> Information for Debtors & Bankrupts

_bankruptcy/Information for Stakeholders/bankruptcy-information-sheet-for-creditors.md
Hi Serene, please assist to approve the request. Thank you
=> Bankruptcy Information Sheet for Creditors

_debt-repayment-scheme/Forms/forms-bankruptcy-act.md, _debt-repayment-scheme/Forms/forms-insolvency-restructuring-and-dissolution-act-wef-30-july-2020.md
=> Notice of appeal BA

_bankruptcy/Filing for Bankruptcy (2).md, _bankruptcy/collection.yml
Dear Zai,
For your approval please.
Thank you
Serene
=> Filing for Bankruptcy (2)

_bankruptcy/Forms/BR Forms IRDA (wef 1 November 2023) (Under Maintenance).md, _bankruptcy/Forms/PIR Forms IRDA (wef 1 November 2023) (Under Maintenance).md, _bankruptcy/Forms/PIR Forms IRDA (wef 1 November 2023).md, _bankruptcy/collection.yml
Dear Zainuriah,
For your approval please.
Thank you
Serene
=> Updating Forms Page

_bankruptcy/Annulment and Discharge Listings.md
Dear Serene, For your approval please. Thank you.
=> Upload annulment and discharge listings

_bankruptcy/Information for Stakeholders/bankruptcy-information-sheet-for-creditors.md
Hi Serene, for your approval please. Thank you
=> Remove “Bankruptcy Information Sheet for Creditors” 

_bankruptcy/Bankruptcy Rehabilitation Programme by Credit Counselling Singapore (CCS).md
Hi Serene, for your approval please. Thanks
=> Update CCS info

_bankruptcy/Annulment and Discharge Listings.md
=> Annulment and Discharge Listings (Week 48)

_debt-repayment-scheme/information-for-debtors.md
Hi Nazirah, please assist to approve. Thank you .
=> Removal of sentence in DRS website

_bankruptcy/Information for Stakeholders/information-for-creditors.md, _bankruptcy/alternatives-to-bankruptcy.md, _bankruptcy/pre-bankruptcy.md, _debt-repayment-scheme/information-for-debtors.md, _unclaimed-monies/bankruptcy.md
Adding extra footnote on charges for 1800
=> Addition of footnote for 1800

_unclaimed-monies/bankruptcy.md
Amendment to footnote for unclaimed monies reference to hotline
=> Amendment to footnote
